name: 'Azure Container Registry Login'
description: 'Log in to Azure Container Registry (ACR) or any private container registry'
inputs: 
  username:
    description: 'Container registry username'
    required: true
    default: ''
  password:
    description: 'Container registry password'
    required: true
    default: ''
  login-server:
    description: 'Container registry server url'
    required: true
    default: 'https://index.docker.io/v1/'
  azcliversion:
    description: 'The azure cli version to use'
    required: false
    default: null
branding:
  color: 'green'
runs:
  using: 'node12'
  main: 'lib/login.js'
